### ISSUE TITLE
May I get some help from you，about osc tweak?

### ISSUE THREAD

**Issue by techz1** [maoiscat/mpv-osc-morden#14]
I like the icon style of this theme, except the layout, because the space at the bottom is a bit high, I want to modify it to be similar to the usual web player layout and move the bottom menu down, can you tell me what key parts to modify?

**Comment by 1-minute-to-midnight** [comment]
or you can use ![my config](https://github.com/1-minute-to-midnight/mpv-morden-x-compact)

**Comment by techz1** [comment]
> or you can use ![my config](https://github.com/1-minute-to-midnight/mpv-morden-x-compact)

Thank you very much for your help, it helped me a lot. I'll try to modify and test it, thanks again.
