### ISSUE TITLE
OSC (Seekbar) is not visible while seeking.

### ISSUE THREAD

**Issue by captaingreen82** [maoiscat/mpv-osc-morden#2]
OSC (Seekbar) is not visible while seeking. It is visible only there is any mouse movement. but when I seek through keyboard seekbar is not visible. Plz help me with this.

**Comment by hooke007** [comment]
>OSC (Seekbar) is not visible while seeking.

If you mean using keyboard to seek. Indeed , mpv do not have this function. There is the similar feature request in the mpv issues list.

**Comment by XCongoAlpha** [comment]
There is a [script for showing OSC when seeking](https://github.com/jaseg/python-mpv/issues/124#issuecomment-660623068) but it shows the default osc.lua instead of mordenx.lua. 

Is there any way for it to show modernx.lua instead?

**Comment by perdakovich** [comment]
@XCongoAlpha 

I too have been searching for this solution and am now in the same position as you. Were you able to solve the problem?

**Comment by Keith94** [comment]
You can use the new fork [ModernZ](https://github.com/Samillion/ModernZ) with its `osc_on_seek=yes` option.
