### ISSUE TITLE
play/pause icons switched

### ISSUE THREAD

**Issue by wetcabbage** [maoiscat/mpv-osc-morden#5]
yo, it's probably because i have mpv set to auto-play when a file is launched, but now whenever a video is playing, the play (triangle) icon shows, and whenever it is paused, the pause icon shows (the two vertical lines).

**Comment by maoiscat** [comment]
it's not the autoplay issue, it works right the way you see.

or rather, if you want a swapped button display, then swap line 1183 and 1185 in the file
