### ISSUE TITLE
请问想调整一下控制栏的高度和透明度，应该更改哪个地方？

### ISSUE THREAD

**Issue by chwt163** [maoiscat/mpv-osc-morden#6]
还有，没有打开文件时的那个大图标圈圈也想去掉。

另外，跟你推荐一下 mpv.net，支持 mpv osc 主题，支持右键菜单：
https://github.com/stax76/mpv.net

这里有我改好的中文菜单：
https://github.com/chwt163/mpv.net-Right-click-menu-CN

**Comment by chwt163** [comment]
[osc.zip](https://github.com/maoiscat/mpv-osc-morden/files/7712931/osc.zip)
我改了一下，控制栏高度搞好了，但有几个问题一直没弄好，大佬能不能帮我检查一下：
一个是想把倒数第二个按钮改成音量按钮
另一个是 title 只在暂停的时候才显示，能让它一直显示在控制栏里面吗？并且能不能自动省略长文件名？或者像默认osc那样自动缩小字体？
现在如果文件名很长，显示会越界。
最后一个就是透明度，一直没有找到。。。
谢谢！

**Comment by maoiscat** [comment]
建议你先研究一下原版osc.lua[https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua](url)
透明度由osc_styles.TransBG设置，是ASS/SSA字幕格式
