### ISSUE TITLE
Weird first page 

### ISSUE THREAD

**Issue by KARTIKUNNI** [maoiscat/mpv-osc-morden#7]
I'm on windows 10 installed the video player works fine but the first page is goofy
![Capture](https://user-images.githubusercontent.com/75520396/150476486-6db6bdb3-44f8-49e7-8bfb-ad683a4be092.PNG)

**Comment by maoiscat** [comment]
Why don't you just follow the instructions 

in mpv.conf
osc=no

在 2022-01-21 14:19:34，"kartik unni" ***@***.***> 写道：


I'm on windows 10 installed the video player works fine but the first page is goofy


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
