### ISSUE TITLE
Chapters not showing

### ISSUE THREAD

**Issue by RafeeDaBoy** [maoiscat/mpv-osc-morden#8]
When hovering over a certain chapter, the name of the chapter is not displayed.

![image](https://user-images.githubusercontent.com/69535896/151658551-e918bd09-88b9-426f-a812-0ec72ad51370.png)
![image](https://user-images.githubusercontent.com/69535896/151658554-8e0a997b-34cf-4487-b152-809af97e2cdc.png)

**Comment by maoiscat** [comment]
That's correct. There is no such feature.
