### ISSUE TITLE
How to hide OSC when paused?

### ISSUE THREAD

**Issue by sgalpha01** [maoiscat/mpv-osc-morden#9]
When I pause the video, the bottom bar appears. I want to hide that. How to achieve that?
![image](https://user-images.githubusercontent.com/42481964/151673872-7b7cfed8-1840-4a17-a11f-ecc00d736c21.png)

**Comment by maoiscat** [comment]
line 38: showtitle = false

**Comment by sgalpha01** [comment]
Thanks Man!
